/**
 * generated by Xtext 2.14.0
 */
package ca.jahed.papyrusrt.persistence.dsl.persist;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Folder Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement#getContents <em>Contents</em>}</li>
 *   <li>{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement#getCalls <em>Calls</em>}</li>
 * </ul>
 *
 * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#getCreateFolderStatement()
 * @model
 * @generated
 */
public interface CreateFolderStatement extends CreateStatement
{
  /**
   * Returns the value of the '<em><b>Contents</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateStatement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contents</em>' containment reference list.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#getCreateFolderStatement_Contents()
   * @model containment="true"
   * @generated
   */
  EList<CreateStatement> getContents();

  /**
   * Returns the value of the '<em><b>Calls</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.papyrusrt.persistence.dsl.persist.CallStatement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calls</em>' containment reference list.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#getCreateFolderStatement_Calls()
   * @model containment="true"
   * @generated
   */
  EList<CallStatement> getCalls();

} // CreateFolderStatement
