/**
 * generated by Xtext 2.14.0
 */
package ca.jahed.papyrusrt.persistence.dsl.persist;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Each Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getClass_ <em>Class</em>}</li>
 *   <li>{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getContents <em>Contents</em>}</li>
 *   <li>{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getCalls <em>Calls</em>}</li>
 * </ul>
 *
 * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#getForEachStatement()
 * @model
 * @generated
 */
public interface ForEachStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class</em>' containment reference.
   * @see #setClass(EClassName)
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#getForEachStatement_Class()
   * @model containment="true"
   * @generated
   */
  EClassName getClass_();

  /**
   * Sets the value of the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getClass_ <em>Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class</em>' containment reference.
   * @see #getClass_()
   * @generated
   */
  void setClass(EClassName value);

  /**
   * Returns the value of the '<em><b>Contents</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateStatement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contents</em>' containment reference list.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#getForEachStatement_Contents()
   * @model containment="true"
   * @generated
   */
  EList<CreateStatement> getContents();

  /**
   * Returns the value of the '<em><b>Calls</b></em>' containment reference list.
   * The list contents are of type {@link ca.jahed.papyrusrt.persistence.dsl.persist.CallStatement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calls</em>' containment reference list.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#getForEachStatement_Calls()
   * @model containment="true"
   * @generated
   */
  EList<CallStatement> getCalls();

} // ForEachStatement
