/**
 * generated by Xtext 2.14.0
 */
package ca.jahed.papyrusrt.persistence.dsl.persist;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistFactory
 * @model kind="package"
 * @generated
 */
public interface PersistPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "persist";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.jahed.ca/papyrusrt/persistence/dsl/Persist";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "persist";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PersistPackage eINSTANCE = ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl.init();

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistImpl <em>Persist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getPersist()
   * @generated
   */
  int PERSIST = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSIST__MODEL = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSIST__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Persist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.RuleStatementImpl <em>Rule Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.RuleStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getRuleStatement()
   * @generated
   */
  int RULE_STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_STATEMENT__ID = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_STATEMENT__RULES = 1;

  /**
   * The number of structural features of the '<em>Rule Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.ForEachStatementImpl <em>For Each Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.ForEachStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getForEachStatement()
   * @generated
   */
  int FOR_EACH_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_STATEMENT__CLASS = 0;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_STATEMENT__CONTENTS = 1;

  /**
   * The feature id for the '<em><b>Calls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_STATEMENT__CALLS = 2;

  /**
   * The number of structural features of the '<em>For Each Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateStatementImpl <em>Create Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCreateStatement()
   * @generated
   */
  int CREATE_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_STATEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Create Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFolderStatementImpl <em>Create Folder Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFolderStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCreateFolderStatement()
   * @generated
   */
  int CREATE_FOLDER_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FOLDER_STATEMENT__NAME = CREATE_STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FOLDER_STATEMENT__CONTENTS = CREATE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Calls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FOLDER_STATEMENT__CALLS = CREATE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Create Folder Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FOLDER_STATEMENT_FEATURE_COUNT = CREATE_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFileStatementImpl <em>Create File Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFileStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCreateFileStatement()
   * @generated
   */
  int CREATE_FILE_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FILE_STATEMENT__NAME = CREATE_STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Included Referencing</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FILE_STATEMENT__INCLUDED_REFERENCING = CREATE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Included Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES = CREATE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Create File Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FILE_STATEMENT_FEATURE_COUNT = CREATE_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.FileNameImpl <em>File Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.FileNameImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getFileName()
   * @generated
   */
  int FILE_NAME = 6;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_NAME__PREFIX = 0;

  /**
   * The feature id for the '<em><b>Attr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_NAME__ATTR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_NAME__RIGHT = 2;

  /**
   * The number of structural features of the '<em>File Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_NAME_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.IncludeStatementImpl <em>Include Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.IncludeStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getIncludeStatement()
   * @generated
   */
  int INCLUDE_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Included</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE_STATEMENT__INCLUDED = 0;

  /**
   * The number of structural features of the '<em>Include Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.WithStatementImpl <em>With Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.WithStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getWithStatement()
   * @generated
   */
  int WITH_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Included</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH_STATEMENT__INCLUDED = 0;

  /**
   * The number of structural features of the '<em>With Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CallStatementImpl <em>Call Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CallStatementImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCallStatement()
   * @generated
   */
  int CALL_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Rules</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_STATEMENT__RULES = 0;

  /**
   * The number of structural features of the '<em>Call Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.EClassNameImpl <em>EClass Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.EClassNameImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getEClassName()
   * @generated
   */
  int ECLASS_NAME = 10;

  /**
   * The feature id for the '<em><b>Base</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECLASS_NAME__BASE = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECLASS_NAME__FIELDS = 1;

  /**
   * The number of structural features of the '<em>EClass Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECLASS_NAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.EAttributeNameImpl <em>EAttribute Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.EAttributeNameImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getEAttributeName()
   * @generated
   */
  int EATTRIBUTE_NAME = 11;

  /**
   * The feature id for the '<em><b>Base</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EATTRIBUTE_NAME__BASE = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EATTRIBUTE_NAME__FIELDS = 1;

  /**
   * The number of structural features of the '<em>EAttribute Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EATTRIBUTE_NAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.EReferenceNameImpl <em>EReference Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.EReferenceNameImpl
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getEReferenceName()
   * @generated
   */
  int EREFERENCE_NAME = 12;

  /**
   * The feature id for the '<em><b>Base</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EREFERENCE_NAME__BASE = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EREFERENCE_NAME__FIELDS = 1;

  /**
   * The number of structural features of the '<em>EReference Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EREFERENCE_NAME_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.Persist <em>Persist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Persist</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.Persist
   * @generated
   */
  EClass getPersist();

  /**
   * Returns the meta object for the attribute '{@link ca.jahed.papyrusrt.persistence.dsl.persist.Persist#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Model</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.Persist#getModel()
   * @see #getPersist()
   * @generated
   */
  EAttribute getPersist_Model();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.Persist#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.Persist#getStatements()
   * @see #getPersist()
   * @generated
   */
  EReference getPersist_Statements();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.RuleStatement <em>Rule Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.RuleStatement
   * @generated
   */
  EClass getRuleStatement();

  /**
   * Returns the meta object for the attribute '{@link ca.jahed.papyrusrt.persistence.dsl.persist.RuleStatement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.RuleStatement#getId()
   * @see #getRuleStatement()
   * @generated
   */
  EAttribute getRuleStatement_Id();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.RuleStatement#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.RuleStatement#getRules()
   * @see #getRuleStatement()
   * @generated
   */
  EReference getRuleStatement_Rules();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement <em>For Each Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Each Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement
   * @generated
   */
  EClass getForEachStatement();

  /**
   * Returns the meta object for the containment reference '{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getClass_ <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Class</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getClass_()
   * @see #getForEachStatement()
   * @generated
   */
  EReference getForEachStatement_Class();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getContents()
   * @see #getForEachStatement()
   * @generated
   */
  EReference getForEachStatement_Contents();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getCalls <em>Calls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Calls</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement#getCalls()
   * @see #getForEachStatement()
   * @generated
   */
  EReference getForEachStatement_Calls();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateStatement <em>Create Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateStatement
   * @generated
   */
  EClass getCreateStatement();

  /**
   * Returns the meta object for the containment reference '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateStatement#getName()
   * @see #getCreateStatement()
   * @generated
   */
  EReference getCreateStatement_Name();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement <em>Create Folder Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Folder Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement
   * @generated
   */
  EClass getCreateFolderStatement();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement#getContents()
   * @see #getCreateFolderStatement()
   * @generated
   */
  EReference getCreateFolderStatement_Contents();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement#getCalls <em>Calls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Calls</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement#getCalls()
   * @see #getCreateFolderStatement()
   * @generated
   */
  EReference getCreateFolderStatement_Calls();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement <em>Create File Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create File Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement
   * @generated
   */
  EClass getCreateFileStatement();

  /**
   * Returns the meta object for the containment reference '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement#getIncludedReferencing <em>Included Referencing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Included Referencing</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement#getIncludedReferencing()
   * @see #getCreateFileStatement()
   * @generated
   */
  EReference getCreateFileStatement_IncludedReferencing();

  /**
   * Returns the meta object for the containment reference '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement#getIncludedAttributes <em>Included Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Included Attributes</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement#getIncludedAttributes()
   * @see #getCreateFileStatement()
   * @generated
   */
  EReference getCreateFileStatement_IncludedAttributes();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.FileName <em>File Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File Name</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.FileName
   * @generated
   */
  EClass getFileName();

  /**
   * Returns the meta object for the attribute '{@link ca.jahed.papyrusrt.persistence.dsl.persist.FileName#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.FileName#getPrefix()
   * @see #getFileName()
   * @generated
   */
  EAttribute getFileName_Prefix();

  /**
   * Returns the meta object for the containment reference '{@link ca.jahed.papyrusrt.persistence.dsl.persist.FileName#getAttr <em>Attr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attr</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.FileName#getAttr()
   * @see #getFileName()
   * @generated
   */
  EReference getFileName_Attr();

  /**
   * Returns the meta object for the containment reference '{@link ca.jahed.papyrusrt.persistence.dsl.persist.FileName#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.FileName#getRight()
   * @see #getFileName()
   * @generated
   */
  EReference getFileName_Right();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.IncludeStatement <em>Include Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Include Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.IncludeStatement
   * @generated
   */
  EClass getIncludeStatement();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.IncludeStatement#getIncluded <em>Included</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Included</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.IncludeStatement#getIncluded()
   * @see #getIncludeStatement()
   * @generated
   */
  EReference getIncludeStatement_Included();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.WithStatement <em>With Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>With Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.WithStatement
   * @generated
   */
  EClass getWithStatement();

  /**
   * Returns the meta object for the containment reference list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.WithStatement#getIncluded <em>Included</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Included</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.WithStatement#getIncluded()
   * @see #getWithStatement()
   * @generated
   */
  EReference getWithStatement_Included();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CallStatement <em>Call Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call Statement</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CallStatement
   * @generated
   */
  EClass getCallStatement();

  /**
   * Returns the meta object for the attribute list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.CallStatement#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Rules</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.CallStatement#getRules()
   * @see #getCallStatement()
   * @generated
   */
  EAttribute getCallStatement_Rules();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EClassName <em>EClass Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EClass Name</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EClassName
   * @generated
   */
  EClass getEClassName();

  /**
   * Returns the meta object for the attribute '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EClassName#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Base</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EClassName#getBase()
   * @see #getEClassName()
   * @generated
   */
  EAttribute getEClassName_Base();

  /**
   * Returns the meta object for the attribute list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EClassName#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Fields</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EClassName#getFields()
   * @see #getEClassName()
   * @generated
   */
  EAttribute getEClassName_Fields();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EAttributeName <em>EAttribute Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EAttribute Name</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EAttributeName
   * @generated
   */
  EClass getEAttributeName();

  /**
   * Returns the meta object for the attribute '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EAttributeName#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Base</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EAttributeName#getBase()
   * @see #getEAttributeName()
   * @generated
   */
  EAttribute getEAttributeName_Base();

  /**
   * Returns the meta object for the attribute list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EAttributeName#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Fields</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EAttributeName#getFields()
   * @see #getEAttributeName()
   * @generated
   */
  EAttribute getEAttributeName_Fields();

  /**
   * Returns the meta object for class '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EReferenceName <em>EReference Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EReference Name</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EReferenceName
   * @generated
   */
  EClass getEReferenceName();

  /**
   * Returns the meta object for the attribute '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EReferenceName#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Base</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EReferenceName#getBase()
   * @see #getEReferenceName()
   * @generated
   */
  EAttribute getEReferenceName_Base();

  /**
   * Returns the meta object for the attribute list '{@link ca.jahed.papyrusrt.persistence.dsl.persist.EReferenceName#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Fields</em>'.
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.EReferenceName#getFields()
   * @see #getEReferenceName()
   * @generated
   */
  EAttribute getEReferenceName_Fields();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PersistFactory getPersistFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistImpl <em>Persist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getPersist()
     * @generated
     */
    EClass PERSIST = eINSTANCE.getPersist();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSIST__MODEL = eINSTANCE.getPersist_Model();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSIST__STATEMENTS = eINSTANCE.getPersist_Statements();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.RuleStatementImpl <em>Rule Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.RuleStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getRuleStatement()
     * @generated
     */
    EClass RULE_STATEMENT = eINSTANCE.getRuleStatement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_STATEMENT__ID = eINSTANCE.getRuleStatement_Id();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_STATEMENT__RULES = eINSTANCE.getRuleStatement_Rules();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.ForEachStatementImpl <em>For Each Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.ForEachStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getForEachStatement()
     * @generated
     */
    EClass FOR_EACH_STATEMENT = eINSTANCE.getForEachStatement();

    /**
     * The meta object literal for the '<em><b>Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_STATEMENT__CLASS = eINSTANCE.getForEachStatement_Class();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_STATEMENT__CONTENTS = eINSTANCE.getForEachStatement_Contents();

    /**
     * The meta object literal for the '<em><b>Calls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_STATEMENT__CALLS = eINSTANCE.getForEachStatement_Calls();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateStatementImpl <em>Create Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCreateStatement()
     * @generated
     */
    EClass CREATE_STATEMENT = eINSTANCE.getCreateStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_STATEMENT__NAME = eINSTANCE.getCreateStatement_Name();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFolderStatementImpl <em>Create Folder Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFolderStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCreateFolderStatement()
     * @generated
     */
    EClass CREATE_FOLDER_STATEMENT = eINSTANCE.getCreateFolderStatement();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_FOLDER_STATEMENT__CONTENTS = eINSTANCE.getCreateFolderStatement_Contents();

    /**
     * The meta object literal for the '<em><b>Calls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_FOLDER_STATEMENT__CALLS = eINSTANCE.getCreateFolderStatement_Calls();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFileStatementImpl <em>Create File Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFileStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCreateFileStatement()
     * @generated
     */
    EClass CREATE_FILE_STATEMENT = eINSTANCE.getCreateFileStatement();

    /**
     * The meta object literal for the '<em><b>Included Referencing</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_FILE_STATEMENT__INCLUDED_REFERENCING = eINSTANCE.getCreateFileStatement_IncludedReferencing();

    /**
     * The meta object literal for the '<em><b>Included Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES = eINSTANCE.getCreateFileStatement_IncludedAttributes();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.FileNameImpl <em>File Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.FileNameImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getFileName()
     * @generated
     */
    EClass FILE_NAME = eINSTANCE.getFileName();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILE_NAME__PREFIX = eINSTANCE.getFileName_Prefix();

    /**
     * The meta object literal for the '<em><b>Attr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE_NAME__ATTR = eINSTANCE.getFileName_Attr();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE_NAME__RIGHT = eINSTANCE.getFileName_Right();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.IncludeStatementImpl <em>Include Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.IncludeStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getIncludeStatement()
     * @generated
     */
    EClass INCLUDE_STATEMENT = eINSTANCE.getIncludeStatement();

    /**
     * The meta object literal for the '<em><b>Included</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INCLUDE_STATEMENT__INCLUDED = eINSTANCE.getIncludeStatement_Included();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.WithStatementImpl <em>With Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.WithStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getWithStatement()
     * @generated
     */
    EClass WITH_STATEMENT = eINSTANCE.getWithStatement();

    /**
     * The meta object literal for the '<em><b>Included</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WITH_STATEMENT__INCLUDED = eINSTANCE.getWithStatement_Included();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CallStatementImpl <em>Call Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.CallStatementImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getCallStatement()
     * @generated
     */
    EClass CALL_STATEMENT = eINSTANCE.getCallStatement();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALL_STATEMENT__RULES = eINSTANCE.getCallStatement_Rules();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.EClassNameImpl <em>EClass Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.EClassNameImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getEClassName()
     * @generated
     */
    EClass ECLASS_NAME = eINSTANCE.getEClassName();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECLASS_NAME__BASE = eINSTANCE.getEClassName_Base();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECLASS_NAME__FIELDS = eINSTANCE.getEClassName_Fields();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.EAttributeNameImpl <em>EAttribute Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.EAttributeNameImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getEAttributeName()
     * @generated
     */
    EClass EATTRIBUTE_NAME = eINSTANCE.getEAttributeName();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EATTRIBUTE_NAME__BASE = eINSTANCE.getEAttributeName_Base();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EATTRIBUTE_NAME__FIELDS = eINSTANCE.getEAttributeName_Fields();

    /**
     * The meta object literal for the '{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.EReferenceNameImpl <em>EReference Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.EReferenceNameImpl
     * @see ca.jahed.papyrusrt.persistence.dsl.persist.impl.PersistPackageImpl#getEReferenceName()
     * @generated
     */
    EClass EREFERENCE_NAME = eINSTANCE.getEReferenceName();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EREFERENCE_NAME__BASE = eINSTANCE.getEReferenceName_Base();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EREFERENCE_NAME__FIELDS = eINSTANCE.getEReferenceName_Fields();

  }

} //PersistPackage
