/**
 * generated by Xtext 2.14.0
 */
package ca.jahed.papyrusrt.persistence.dsl.persist.impl;

import ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.IncludeStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage;
import ca.jahed.papyrusrt.persistence.dsl.persist.WithStatement;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Create File Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFileStatementImpl#getIncludedReferencing <em>Included Referencing</em>}</li>
 *   <li>{@link ca.jahed.papyrusrt.persistence.dsl.persist.impl.CreateFileStatementImpl#getIncludedAttributes <em>Included Attributes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CreateFileStatementImpl extends CreateStatementImpl implements CreateFileStatement
{
  /**
   * The cached value of the '{@link #getIncludedReferencing() <em>Included Referencing</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncludedReferencing()
   * @generated
   * @ordered
   */
  protected WithStatement includedReferencing;

  /**
   * The cached value of the '{@link #getIncludedAttributes() <em>Included Attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncludedAttributes()
   * @generated
   * @ordered
   */
  protected IncludeStatement includedAttributes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CreateFileStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PersistPackage.Literals.CREATE_FILE_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WithStatement getIncludedReferencing()
  {
    return includedReferencing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIncludedReferencing(WithStatement newIncludedReferencing, NotificationChain msgs)
  {
    WithStatement oldIncludedReferencing = includedReferencing;
    includedReferencing = newIncludedReferencing;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING, oldIncludedReferencing, newIncludedReferencing);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIncludedReferencing(WithStatement newIncludedReferencing)
  {
    if (newIncludedReferencing != includedReferencing)
    {
      NotificationChain msgs = null;
      if (includedReferencing != null)
        msgs = ((InternalEObject)includedReferencing).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING, null, msgs);
      if (newIncludedReferencing != null)
        msgs = ((InternalEObject)newIncludedReferencing).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING, null, msgs);
      msgs = basicSetIncludedReferencing(newIncludedReferencing, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING, newIncludedReferencing, newIncludedReferencing));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IncludeStatement getIncludedAttributes()
  {
    return includedAttributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIncludedAttributes(IncludeStatement newIncludedAttributes, NotificationChain msgs)
  {
    IncludeStatement oldIncludedAttributes = includedAttributes;
    includedAttributes = newIncludedAttributes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES, oldIncludedAttributes, newIncludedAttributes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIncludedAttributes(IncludeStatement newIncludedAttributes)
  {
    if (newIncludedAttributes != includedAttributes)
    {
      NotificationChain msgs = null;
      if (includedAttributes != null)
        msgs = ((InternalEObject)includedAttributes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES, null, msgs);
      if (newIncludedAttributes != null)
        msgs = ((InternalEObject)newIncludedAttributes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES, null, msgs);
      msgs = basicSetIncludedAttributes(newIncludedAttributes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES, newIncludedAttributes, newIncludedAttributes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING:
        return basicSetIncludedReferencing(null, msgs);
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES:
        return basicSetIncludedAttributes(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING:
        return getIncludedReferencing();
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES:
        return getIncludedAttributes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING:
        setIncludedReferencing((WithStatement)newValue);
        return;
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES:
        setIncludedAttributes((IncludeStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING:
        setIncludedReferencing((WithStatement)null);
        return;
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES:
        setIncludedAttributes((IncludeStatement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_REFERENCING:
        return includedReferencing != null;
      case PersistPackage.CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES:
        return includedAttributes != null;
    }
    return super.eIsSet(featureID);
  }

} //CreateFileStatementImpl
