/**
 * generated by Xtext 2.14.0
 */
package ca.jahed.papyrusrt.persistence.dsl.persist.impl;

import ca.jahed.papyrusrt.persistence.dsl.persist.CallStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.CreateFileStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.CreateFolderStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.CreateStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.EAttributeName;
import ca.jahed.papyrusrt.persistence.dsl.persist.EClassName;
import ca.jahed.papyrusrt.persistence.dsl.persist.EReferenceName;
import ca.jahed.papyrusrt.persistence.dsl.persist.FileName;
import ca.jahed.papyrusrt.persistence.dsl.persist.ForEachStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.IncludeStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.Persist;
import ca.jahed.papyrusrt.persistence.dsl.persist.PersistFactory;
import ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage;
import ca.jahed.papyrusrt.persistence.dsl.persist.RuleStatement;
import ca.jahed.papyrusrt.persistence.dsl.persist.WithStatement;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PersistPackageImpl extends EPackageImpl implements PersistPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass persistEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ruleStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass forEachStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass createStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass createFolderStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass createFileStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fileNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass includeStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass withStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass callStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eClassNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eAttributeNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eReferenceNameEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see ca.jahed.papyrusrt.persistence.dsl.persist.PersistPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private PersistPackageImpl()
  {
    super(eNS_URI, PersistFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link PersistPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static PersistPackage init()
  {
    if (isInited) return (PersistPackage)EPackage.Registry.INSTANCE.getEPackage(PersistPackage.eNS_URI);

    // Obtain or create and register package
    PersistPackageImpl thePersistPackage = (PersistPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof PersistPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new PersistPackageImpl());

    isInited = true;

    // Create package meta-data objects
    thePersistPackage.createPackageContents();

    // Initialize created meta-data
    thePersistPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    thePersistPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(PersistPackage.eNS_URI, thePersistPackage);
    return thePersistPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPersist()
  {
    return persistEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPersist_Model()
  {
    return (EAttribute)persistEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPersist_Statements()
  {
    return (EReference)persistEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRuleStatement()
  {
    return ruleStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRuleStatement_Id()
  {
    return (EAttribute)ruleStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleStatement_Rules()
  {
    return (EReference)ruleStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getForEachStatement()
  {
    return forEachStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getForEachStatement_Class()
  {
    return (EReference)forEachStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getForEachStatement_Contents()
  {
    return (EReference)forEachStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getForEachStatement_Calls()
  {
    return (EReference)forEachStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCreateStatement()
  {
    return createStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCreateStatement_Name()
  {
    return (EReference)createStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCreateFolderStatement()
  {
    return createFolderStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCreateFolderStatement_Contents()
  {
    return (EReference)createFolderStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCreateFolderStatement_Calls()
  {
    return (EReference)createFolderStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCreateFileStatement()
  {
    return createFileStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCreateFileStatement_IncludedReferencing()
  {
    return (EReference)createFileStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCreateFileStatement_IncludedAttributes()
  {
    return (EReference)createFileStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFileName()
  {
    return fileNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFileName_Prefix()
  {
    return (EAttribute)fileNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFileName_Attr()
  {
    return (EReference)fileNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFileName_Right()
  {
    return (EReference)fileNameEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getIncludeStatement()
  {
    return includeStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getIncludeStatement_Included()
  {
    return (EReference)includeStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWithStatement()
  {
    return withStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWithStatement_Included()
  {
    return (EReference)withStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCallStatement()
  {
    return callStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCallStatement_Rules()
  {
    return (EAttribute)callStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEClassName()
  {
    return eClassNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEClassName_Base()
  {
    return (EAttribute)eClassNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEClassName_Fields()
  {
    return (EAttribute)eClassNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEAttributeName()
  {
    return eAttributeNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEAttributeName_Base()
  {
    return (EAttribute)eAttributeNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEAttributeName_Fields()
  {
    return (EAttribute)eAttributeNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEReferenceName()
  {
    return eReferenceNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEReferenceName_Base()
  {
    return (EAttribute)eReferenceNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEReferenceName_Fields()
  {
    return (EAttribute)eReferenceNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PersistFactory getPersistFactory()
  {
    return (PersistFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    persistEClass = createEClass(PERSIST);
    createEAttribute(persistEClass, PERSIST__MODEL);
    createEReference(persistEClass, PERSIST__STATEMENTS);

    ruleStatementEClass = createEClass(RULE_STATEMENT);
    createEAttribute(ruleStatementEClass, RULE_STATEMENT__ID);
    createEReference(ruleStatementEClass, RULE_STATEMENT__RULES);

    forEachStatementEClass = createEClass(FOR_EACH_STATEMENT);
    createEReference(forEachStatementEClass, FOR_EACH_STATEMENT__CLASS);
    createEReference(forEachStatementEClass, FOR_EACH_STATEMENT__CONTENTS);
    createEReference(forEachStatementEClass, FOR_EACH_STATEMENT__CALLS);

    createStatementEClass = createEClass(CREATE_STATEMENT);
    createEReference(createStatementEClass, CREATE_STATEMENT__NAME);

    createFolderStatementEClass = createEClass(CREATE_FOLDER_STATEMENT);
    createEReference(createFolderStatementEClass, CREATE_FOLDER_STATEMENT__CONTENTS);
    createEReference(createFolderStatementEClass, CREATE_FOLDER_STATEMENT__CALLS);

    createFileStatementEClass = createEClass(CREATE_FILE_STATEMENT);
    createEReference(createFileStatementEClass, CREATE_FILE_STATEMENT__INCLUDED_REFERENCING);
    createEReference(createFileStatementEClass, CREATE_FILE_STATEMENT__INCLUDED_ATTRIBUTES);

    fileNameEClass = createEClass(FILE_NAME);
    createEAttribute(fileNameEClass, FILE_NAME__PREFIX);
    createEReference(fileNameEClass, FILE_NAME__ATTR);
    createEReference(fileNameEClass, FILE_NAME__RIGHT);

    includeStatementEClass = createEClass(INCLUDE_STATEMENT);
    createEReference(includeStatementEClass, INCLUDE_STATEMENT__INCLUDED);

    withStatementEClass = createEClass(WITH_STATEMENT);
    createEReference(withStatementEClass, WITH_STATEMENT__INCLUDED);

    callStatementEClass = createEClass(CALL_STATEMENT);
    createEAttribute(callStatementEClass, CALL_STATEMENT__RULES);

    eClassNameEClass = createEClass(ECLASS_NAME);
    createEAttribute(eClassNameEClass, ECLASS_NAME__BASE);
    createEAttribute(eClassNameEClass, ECLASS_NAME__FIELDS);

    eAttributeNameEClass = createEClass(EATTRIBUTE_NAME);
    createEAttribute(eAttributeNameEClass, EATTRIBUTE_NAME__BASE);
    createEAttribute(eAttributeNameEClass, EATTRIBUTE_NAME__FIELDS);

    eReferenceNameEClass = createEClass(EREFERENCE_NAME);
    createEAttribute(eReferenceNameEClass, EREFERENCE_NAME__BASE);
    createEAttribute(eReferenceNameEClass, EREFERENCE_NAME__FIELDS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    createFolderStatementEClass.getESuperTypes().add(this.getCreateStatement());
    createFileStatementEClass.getESuperTypes().add(this.getCreateStatement());

    // Initialize classes and features; add operations and parameters
    initEClass(persistEClass, Persist.class, "Persist", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPersist_Model(), ecorePackage.getEString(), "model", null, 0, 1, Persist.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPersist_Statements(), this.getRuleStatement(), null, "statements", null, 0, -1, Persist.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ruleStatementEClass, RuleStatement.class, "RuleStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRuleStatement_Id(), ecorePackage.getEString(), "id", null, 0, 1, RuleStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleStatement_Rules(), this.getForEachStatement(), null, "rules", null, 0, -1, RuleStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(forEachStatementEClass, ForEachStatement.class, "ForEachStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getForEachStatement_Class(), this.getEClassName(), null, "class", null, 0, 1, ForEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getForEachStatement_Contents(), this.getCreateStatement(), null, "contents", null, 0, -1, ForEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getForEachStatement_Calls(), this.getCallStatement(), null, "calls", null, 0, -1, ForEachStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(createStatementEClass, CreateStatement.class, "CreateStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCreateStatement_Name(), this.getFileName(), null, "name", null, 0, 1, CreateStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(createFolderStatementEClass, CreateFolderStatement.class, "CreateFolderStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCreateFolderStatement_Contents(), this.getCreateStatement(), null, "contents", null, 0, -1, CreateFolderStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCreateFolderStatement_Calls(), this.getCallStatement(), null, "calls", null, 0, -1, CreateFolderStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(createFileStatementEClass, CreateFileStatement.class, "CreateFileStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCreateFileStatement_IncludedReferencing(), this.getWithStatement(), null, "includedReferencing", null, 0, 1, CreateFileStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCreateFileStatement_IncludedAttributes(), this.getIncludeStatement(), null, "includedAttributes", null, 0, 1, CreateFileStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fileNameEClass, FileName.class, "FileName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFileName_Prefix(), ecorePackage.getEString(), "prefix", null, 0, 1, FileName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFileName_Attr(), this.getEAttributeName(), null, "attr", null, 0, 1, FileName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFileName_Right(), this.getFileName(), null, "right", null, 0, 1, FileName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(includeStatementEClass, IncludeStatement.class, "IncludeStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIncludeStatement_Included(), this.getEReferenceName(), null, "included", null, 0, -1, IncludeStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(withStatementEClass, WithStatement.class, "WithStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWithStatement_Included(), this.getEClassName(), null, "included", null, 0, -1, WithStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(callStatementEClass, CallStatement.class, "CallStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCallStatement_Rules(), ecorePackage.getEString(), "rules", null, 0, -1, CallStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eClassNameEClass, EClassName.class, "EClassName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEClassName_Base(), ecorePackage.getEString(), "base", null, 0, 1, EClassName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEClassName_Fields(), ecorePackage.getEString(), "fields", null, 0, -1, EClassName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eAttributeNameEClass, EAttributeName.class, "EAttributeName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEAttributeName_Base(), ecorePackage.getEString(), "base", null, 0, 1, EAttributeName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEAttributeName_Fields(), ecorePackage.getEString(), "fields", null, 0, -1, EAttributeName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eReferenceNameEClass, EReferenceName.class, "EReferenceName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEReferenceName_Base(), ecorePackage.getEString(), "base", null, 0, 1, EReferenceName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEReferenceName_Fields(), ecorePackage.getEString(), "fields", null, 0, -1, EReferenceName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //PersistPackageImpl
