/*
 * generated by Xtext 2.14.0
 */
package ca.jahed.papyrusrt.persistence.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PersistStandaloneSetup extends PersistStandaloneSetupGenerated {

	def static void doSetup() {
		new PersistStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
